# Generated by Django 4.2.6 on 2023-10-07 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('size', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_last_date', models.DateTimeField(null=True)),
                ('comment', models.TextField(blank=True, max_length=120)),
                ('path', models.CharField(null=True)),
                ('download_link', models.CharField(null=True)),
                ('upload', models.FileField(upload_to='test/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
