# Generated by Django 4.2.6 on 2023-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='download_last_date',
            field=models.DateTimeField(default='no downloads'),
        ),
    ]
